ALTER TABLE product ADD FOREIGN KEY (creator_id) REFERENCES creator (id) ON DELETE RESTRICT;

ALTER TABLE purchase ADD FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE RESTRICT;

ALTER TABLE purchase ADD FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE RESTRICT;

ALTER TABLE product_genre ADD FOREIGN KEY ( product_id) REFERENCES product (id) ON DELETE RESTRICT;

ALTER TABLE product_genre ADD FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;

ALTER TABLE customer ADD FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE RESTRICT;

ALTER TABLE staff ADD FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE RESTRICT;

ALTER TABLE creator ADD FOREIGN KEY (id) REFERENCES "user" (id) ON DELETE RESTRICT;