my.param.db="Работа с БД успешно проведена"
default.date.pattern="yyyy-MM-dd HH:mm:ss"

db.driver=org.postgresql.Driver
db.classpath=postgresql-42.3.0.jar
db.url=jdbc:postgresql://localhost:5432/example
db.username=root
db.password=root
db.changeLogFile=./changelog-master.xml
